select char_length("hakoona matata!!!") as Length;
use cm;
show tables;
select * from customers;
select customerName, char_length(customerName) as LengthOfName from customers;
select concat("Hello","duniya","kaisi","ho") as MessageFromUs;
select concat_ws(" ","hello","Raj","Chutiya","hu") as MessageReceived;
select ucase('hello') as UpperCaseMessage;
select upper('hello Bitch') as UpperCaseMessageNew;
select lcase('HELLO BITCHES') as LowerCaseMessage;
select lower('HII HANDSOME RAJ!!') as LowerCaseMessageNew;
select trim("       Raj is great !!!         ") as TrimedMessage;
select substr("sheryians coding vidhayala", 1, 3) as First_three_char;
select insert("sheryians school",11,0,"coding ") as CompleteName;
select insert("sheryians coading school",12,1,"o") as CompleteName;
select replace("hello world", "world", "people") as ReplacedName;
select reverse("Hello") as ReversedString;
select strcmp("hey", "hello") as Result;
select strcmp("hello", "hey") as ResultNew;select strcmp("hello", "hey") as ResultNew;
